Feature/jagtrrz/pos tsearh workshop
AlmuUve/HuMind-final-project pull request #16
Opened 2021-02-24 19:47 UTC by jagtrrz

Componente search con su vista su post y sus validaciones todo correcto en principio.

2021-02-25 15:28 UTC, JimenaEB requested changes

2021-02-25 15:28 UTC, JimenaEB commented on src/api/models.py
> +        user = cls.query.filter_by(id = id).first()
Un buen truco es usar .first_or_404()

2021-02-25 15:28 UTC, JimenaEB commented on src/api/models.py
> +        user = cls.query.filter_by(id = id).first()
Un buen truco es usar .first_or_404()

2021-02-25 15:28 UTC, JimenaEB commented on src/api/models.py
> +        return cls
Creo que te has liado

2021-02-25 15:28 UTC, JimenaEB commented on src/api/models.py
> +        backref=db.backref("workshops", lazy='joined'))
Por qué joined?

2021-02-25 15:28 UTC, JimenaEB commented on src/api/models.py
> +    def to_dict(self, category_list):
yo no le pasaría otro parámetro a parte de self

2021-02-25 15:28 UTC, JimenaEB commented on src/api/models.py
> +        workshop = cls.query.filter_by(id = id).first()
también al ser por id podemos hacer un get

2021-02-25 15:28 UTC, JimenaEB commented on src/api/models.py
> +            new_category_list = Category.get_by_id(category)
lo que te devuelve no es una lista

2021-02-25 15:28 UTC, JimenaEB commented on src/app.py
> +@app.route('/user/company/searchworkshop/<int:id>', methods=['POST'])
la ruta sería comany/id/search...

2021-02-25 15:28 UTC, JimenaEB commented on src/app.py
> +@app.route('/user/psychologist/workshop/<int:id>', methods=['POST'])
lo mismo que abajo

2021-02-25 15:28 UTC, JimenaEB commented on src/front/js/component/searchworkshopform.jsx
> +							id="duration"
Creo que se te ha colado

2021-02-25 15:28 UTC, JimenaEB commented on src/front/js/store/flux.js
> +				console.log(response);
borra los console log

2021-02-25 15:55 UTC, jagtrrz commented on src/api/models.py
> +            new_category_list = Category.get_by_id(category)
No se a que te refieres exactamente con que no me devuelve una lista, lo que hago es crear la lista de categorias... no se si esta bien planteado pero la idea era tener las categorias en una lista para luego en el front poder recorrer esa lista y asi pintar las categorias que tocan en cada workshop. 

Lo que me devuelve esta función es lo que paso en el "to_dict" para ver las categorias como una lista y por su nombre.

2021-02-25 16:05 UTC, jagtrrz commented on src/front/js/component/searchworkshopform.jsx
> +							id="duration"
a cual te refieres?

2021-02-25 16:11 UTC, jagtrrz commented
Jimena he cambiado las cosas que entendia de las issues. Hay un par que he dejado porque no se muy bien a que te refieres exactamente. He comentado las issues para que puedas ver a cuales me refiero.

2021-03-01 11:00 UTC, JimenaEB requested changes
Haz el par de cambios y mergeala :)

2021-03-01 11:00 UTC, JimenaEB commented on src/api/models.py
> +            new_category_list = Category.get_by_id(category)
Esto lo dejamos asó porque está en la rama de Almu apañado

2021-03-01 11:00 UTC, JimenaEB commented on src/app.py
> +        return jsonify(new_user_psy.to_dict()), 200
Estaba bien el 201

2021-03-01 11:00 UTC, JimenaEB commented on src/app.py
> +    return jsonify(new_user_company.to_dict()), 200
Estaba bien el 201

2021-03-01 11:00 UTC, JimenaEB commented on src/front/js/component/searchworkshopform.jsx
> +							id="duration"
el id

2021-03-01 13:49 UTC, merged