Get workshops finished
AlmuUve/HuMind-final-project pull request #31
Opened 2021-03-02 10:12 UTC by AlmuUve

Can see all workshops in psychologists profiles

2021-03-02 15:23 UTC, JimenaEB requested changes
Repasa que todo este bien por fi :)

2021-03-02 15:23 UTC, JimenaEB commented on src/api/models.py
> +        return target.is_active
Devuelve todo el user, target, no solo el is_active

2021-03-02 15:23 UTC, JimenaEB commented on src/api/models.py
> +        workshop_by_psychologist_id = cls.query.filter_by(user_psychologist_id = id)
Debería ser una lista con todos los workshops de esa persona

2021-03-02 15:23 UTC, JimenaEB commented on src/app.py
> +
¿Que ha pasado en este fichero?

2021-03-02 15:23 UTC, JimenaEB commented on src/front/js/component/workshopCard.js
> +					<span className="pax">Pax: {props.item.max_people}</span>
pax como nombre de clase css...

2021-03-02 15:23 UTC, JimenaEB commented on src/front/styles/index.scss
> +.details{
si son los detalles del workshop usa workshop--details

2021-03-02 15:30 UTC, AlmuUve commented on src/api/models.py
> +        return target.is_active
OK!

2021-03-02 15:40 UTC, AlmuUve commented on src/api/models.py
> +        workshop_by_psychologist_id = cls.query.filter_by(user_psychologist_id = id)
Lo tenía como lista, pero luego en la app no me dejaba trabajar con una lista...

2021-03-02 15:43 UTC, AlmuUve commented on src/front/js/component/workshopCard.js
> +					<span className="pax">Pax: {props.item.max_people}</span>
cambiado a maxPeople ^^'

2021-03-02 15:43 UTC, AlmuUve commented on src/front/styles/index.scss
> +.details{
hecho :)

2021-03-02 16:23 UTC, JimenaEB commented on src/api/models.py
> +        workshop_by_psychologist_id = cls.query.filter_by(user_psychologist_id = id)
porque debes hacer .all() en la query

2021-03-02 16:23 UTC, JimenaEB commented
Recuerda mergear main en tu rama ahora que está bien

2021-03-04 14:42 UTC, AlmuUve commented
> Repasa que todo este bien por fi :)

It is :__)

2021-03-08 08:20 UTC, merged