methods GET for psychologist users and combination of user and user_p…
AlmuUve/HuMind-final-project pull request #7
Opened 2021-02-19 12:10 UTC by jagtrrz

Metodo GET para usuarios psicologos y combinacion de diccionarios de User y User_psychologist

2021-02-19 15:25 UTC, JimenaEB commented
Para solucionar el conflicto mergeate main en esta rama. Haz esto siempre antes de hacer un PR

2021-02-19 15:37 UTC, JimenaEB requested changes

2021-02-19 15:37 UTC, JimenaEB commented on src/api/models.py
> +            "is_active": True,
Estas forzando que is_active sea True aunque no lo sea

2021-02-19 15:37 UTC, JimenaEB commented on src/api/models.py
> +        user_psychologit = cls.query.filter_by(user_id=user).first()
Puedes hacer un método que coja lo de la tabla user y lo de psicologo a la vez

2021-02-19 15:37 UTC, JimenaEB commented on src/app.py
>  @app.route('/user/<int:id>/psychologist', methods=['POST'])
No me gusta esta ruta, mejor /user/psy.../id es más acorde con REST

2021-02-19 15:37 UTC, JimenaEB commented on src/app.py
>  @app.route('/user/<int:id>/psychologist', methods=['POST'])
También hemos dicho que aun mejor hacer el POST en /user y que sea igual para todas

2021-02-19 15:37 UTC, JimenaEB commented on src/app.py
> +@app.route('/user/<int:id>/psychologist', methods=['GET'])
La ruta sería user/psy.../id

2021-02-19 15:37 UTC, JimenaEB commented on src/app.py
> +    print(user_psychologist)
Borra los prints al subir las cosas

2021-02-19 15:37 UTC, JimenaEB commented on src/app.py
> +    return jsonify(user_psychologist.to_dict(user)), 200
No deberías necesitar pasar user

2021-02-19 15:37 UTC, JimenaEB commented on src/front/js/component/profilecard.jsx
> +export const Profiletemplate = props => {
JS usa camelCase ;P

2021-02-19 15:37 UTC, JimenaEB commented on src/front/js/pages/home.js
> +	let profilePsychologist = userPsychologist.flat().map((item, index) => {
No te hace falta

2021-02-19 15:37 UTC, JimenaEB commented on src/front/js/pages/home.js
> +			<h1>{profilePsychologist}</h1>
Sólo debería haber un h1 por página, por eso hablamos de hacer en css el estilo h1

2021-02-19 15:37 UTC, JimenaEB commented on src/front/js/store/flux.js
> +			urlGetUserPsychologist: "https://3001-aquamarine-cattle-vxa3ls0l.ws-eu03.gitpod.io/user/11/psychologist",
Constantes fuera del store

2021-02-19 15:37 UTC, JimenaEB commented on src/front/js/store/flux.js
> +					console.log(getStore().userPsychologist);
Sólo necesitas un get

2021-02-22 09:23 UTC, JimenaEB commented
Acuerdate siempre de mergear main en tu rama antes de hacer una PR :)

2021-02-22 09:23 UTC, JimenaEB approved these changes

2021-02-25 16:12 UTC, jagtrrz commented
Jimena esta rama ya esta en main. Lo que ahora veo es que me dices que haga un solo GET para psicologos y compañias?

2021-03-01 10:53 UTC, JimenaEB approved these changes

2021-03-01 15:49 UTC, closed without merging